### ISSUE TITLE
AnalogsEnhancers Causes a left-y analog axis read problem

### ISSUE THREAD

**Issue by RatCheese1608** [Rinnegatamante/AnalogsEnhancer#5]
As the title describes. Only when I use AnalogsEnhancer, my left y axis cannot read until 255. Originally it has a left y 0 drift stick problem however when all my plugins were disabled it was able to read up to 255 without a problem. I tested every single plugin I had and made them to work alone and figured only when I had AnalogsEnhancer on, the y axis only reads up to ~230 or pretty much 255 - (127 - how much drift was going on e.g. it keeps on going to 88).  It doesn't have a problem to read left y 0. 

My config is as shown:
left=54,n;right=36,n,y
And my vita is a PCH-2000@3.65 enso it had the problems even before enso and 3.65 (I recently downgraded to 3.65 from 3.68 to get enso). I used the lua vita tester by [Keinta15](https://github.com/Keinta15/Lua-Vita-Tester).

I will test it again without the WIDE_ANALOG Setting. I require the use of AnalogsEnhancer to fix the left drift stick problem and a eratic stick problem in the right stick. I could replace them but the screws have rusted and when I attempted to screw them out it seems that the rust has start to corrode them and I fear that I might break them.

After test:
I checked it and it allowed me to reach up to 255 without using much force however it did not last long and reset back to 232 as a maximum. I moved on to using the deadzone in remaPSV which allowed me to go up to 248-251 but still goes down to ~235 on some occasions. One of the reasons why I prefer not to use the deadzone supplied by remaPSV is that it has some kind of auto-rounding system (e.g. when it's close to (x,y){255,127}{0,127}{127,0}{127,255} it just rounds it off to there and gets more aggresive on larger deadzone values).

**Comment by Gus-X** [comment]
For the record.
I don't have a solution but I had a similar behavior using a DS4 and I've found the cause, not a solution.

Problem: playing Persona 4 Golden (with Vita sticks) the character walk and run perfectly. Issue was when I've plugged the Vita to the Big Screen using a DS4. Character cannot "run" in some directions (usually forward) no even enabling any AnalogsEnhancer plugin options.

Cause: my Vita stick is not centered, it was a bit "down" from center. So when I pull DS4 stick forward it doesn't reach 255 (because Vita stick is "pressing a bit backwards".

Solution (if you can call it that way): was a wrapped piece of paper between console and stick "pressing a bit forward". Lame...
This way Vita stick is centered and DS4 can reach 255.

Maybe someone else can have this "drift" issue.

Regards!

**Comment by RatCheese1608** [comment]
At this point I just went out of my fear and replaced the sticks. The sticks still suck tho, at least they can run now.
